Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Controller\\AccueilController",
            "name": "AccueilController",
            "summary": "Description\u0020of\u0020AccueilController",
            "url": "classes/App-Controller-AccueilController.html"
        },                {
            "fqsen": "\\App\\Controller\\AccueilController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-AccueilController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\AccueilController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-AccueilController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\AccueilController\u003A\u003Acgu\u0028\u0029",
            "name": "cgu",
            "summary": "",
            "url": "classes/App-Controller-AccueilController.html#method_cgu"
        },                {
            "fqsen": "\\App\\Controller\\AccueilController\u003A\u003A\u0024repository",
            "name": "repository",
            "summary": "",
            "url": "classes/App-Controller-AccueilController.html#property_repository"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminCategoriesController",
            "name": "AdminCategoriesController",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminCategoriesController.html"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminCategoriesController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminCategoriesController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminCategoriesController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminCategoriesController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminCategoriesController\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminCategoriesController.html#method_add"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminCategoriesController\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminCategoriesController.html#method_delete"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminCategoriesController\u003A\u003A\u0024categorieRepository",
            "name": "categorieRepository",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminCategoriesController.html#property_categorieRepository"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminCategoriesController\u003A\u003A\u0024em",
            "name": "em",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminCategoriesController.html#property_em"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminFormationsController",
            "name": "AdminFormationsController",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminFormationsController.html"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminFormationsController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminFormationsController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminFormationsController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminFormationsController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminFormationsController\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminFormationsController.html#method_add"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminFormationsController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminFormationsController.html#method_edit"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminFormationsController\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminFormationsController.html#method_delete"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminFormationsController\u003A\u003A\u0024formationRepository",
            "name": "formationRepository",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminFormationsController.html#property_formationRepository"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminFormationsController\u003A\u003A\u0024em",
            "name": "em",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminFormationsController.html#property_em"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminHomeController",
            "name": "AdminHomeController",
            "summary": "Contr\u00F4leur\u0020Symfony\u0020pour\u0020g\u00E9rer\u0020adminhome.",
            "url": "classes/App-Controller-Admin-AdminHomeController.html"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminHomeController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminHomeController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminPlaylistsController",
            "name": "AdminPlaylistsController",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminPlaylistsController.html"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminPlaylistsController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminPlaylistsController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminPlaylistsController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminPlaylistsController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminPlaylistsController\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminPlaylistsController.html#method_add"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminPlaylistsController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminPlaylistsController.html#method_edit"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminPlaylistsController\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminPlaylistsController.html#method_delete"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminPlaylistsController\u003A\u003A\u0024playlistRepository",
            "name": "playlistRepository",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminPlaylistsController.html#property_playlistRepository"
        },                {
            "fqsen": "\\App\\Controller\\Admin\\AdminPlaylistsController\u003A\u003A\u0024em",
            "name": "em",
            "summary": "",
            "url": "classes/App-Controller-Admin-AdminPlaylistsController.html#property_em"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController",
            "name": "FormationsController",
            "summary": "Controleur\u0020des\u0020formations",
            "url": "classes/App-Controller-FormationsController.html"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-FormationsController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-FormationsController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "",
            "url": "classes/App-Controller-FormationsController.html#method_sort"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003AfindAllContain\u0028\u0029",
            "name": "findAllContain",
            "summary": "",
            "url": "classes/App-Controller-FormationsController.html#method_findAllContain"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003AshowOne\u0028\u0029",
            "name": "showOne",
            "summary": "",
            "url": "classes/App-Controller-FormationsController.html#method_showOne"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003ArenderFormations\u0028\u0029",
            "name": "renderFormations",
            "summary": "",
            "url": "classes/App-Controller-FormationsController.html#method_renderFormations"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003A\u0024formationRepository",
            "name": "formationRepository",
            "summary": "",
            "url": "classes/App-Controller-FormationsController.html#property_formationRepository"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003A\u0024categorieRepository",
            "name": "categorieRepository",
            "summary": "",
            "url": "classes/App-Controller-FormationsController.html#property_categorieRepository"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController",
            "name": "PlaylistsController",
            "summary": "Contr\u00F4leur\u0020Symfony\u0020pour\u0020g\u00E9rer\u0020playlists.",
            "url": "classes/App-Controller-PlaylistsController.html"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#method_sort"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003AfindAllContain\u0028\u0029",
            "name": "findAllContain",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#method_findAllContain"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003ArenderPlaylists\u0028\u0029",
            "name": "renderPlaylists",
            "summary": "Factorisation\u0020de\u0020l\u0027appel\u0020\u00E0\u0020render\u0020pour\u0020\u00E9viter\u0020la\u0020duplication\u0020de\u0020cha\u00EEnes.",
            "url": "classes/App-Controller-PlaylistsController.html#method_renderPlaylists"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003AshowOne\u0028\u0029",
            "name": "showOne",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#method_showOne"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003APLAYLISTS_TEMPLATE",
            "name": "PLAYLISTS_TEMPLATE",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#constant_PLAYLISTS_TEMPLATE"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController",
            "name": "SecurityController",
            "summary": "Contr\u00F4leur\u0020Symfony\u0020pour\u0020g\u00E9rer\u0020security.",
            "url": "classes/App-Controller-SecurityController.html"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "",
            "url": "classes/App-Controller-SecurityController.html#method_login"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "",
            "url": "classes/App-Controller-SecurityController.html#method_logout"
        },                {
            "fqsen": "\\App\\DataFixtures\\AdminUserFixtures",
            "name": "AdminUserFixtures",
            "summary": "Classe\u0020AdminUserFixtures.",
            "url": "classes/App-DataFixtures-AdminUserFixtures.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\AdminUserFixtures\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-DataFixtures-AdminUserFixtures.html#method___construct"
        },                {
            "fqsen": "\\App\\DataFixtures\\AdminUserFixtures\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/App-DataFixtures-AdminUserFixtures.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\AdminUserFixtures\u003A\u003A\u0024hasher",
            "name": "hasher",
            "summary": "",
            "url": "classes/App-DataFixtures-AdminUserFixtures.html#property_hasher"
        },                {
            "fqsen": "\\App\\Entity\\Categorie",
            "name": "Categorie",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AgetFormations\u0028\u0029",
            "name": "getFormations",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_getFormations"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AaddFormation\u0028\u0029",
            "name": "addFormation",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_addFormation"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AremoveFormation\u0028\u0029",
            "name": "removeFormation",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_removeFormation"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#property_name"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003A\u0024formations",
            "name": "formations",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#property_formations"
        },                {
            "fqsen": "\\App\\Entity\\Formation",
            "name": "Formation",
            "summary": "",
            "url": "classes/App-Entity-Formation.html"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetPublishedAt\u0028\u0029",
            "name": "getPublishedAt",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getPublishedAt"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetPublishedAt\u0028\u0029",
            "name": "setPublishedAt",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_setPublishedAt"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetPublishedAtString\u0028\u0029",
            "name": "getPublishedAtString",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getPublishedAtString"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getTitle"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_setTitle"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getDescription"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_setDescription"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetVideoId\u0028\u0029",
            "name": "getVideoId",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getVideoId"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetVideoId\u0028\u0029",
            "name": "setVideoId",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_setVideoId"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetMiniature\u0028\u0029",
            "name": "getMiniature",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getMiniature"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetPicture\u0028\u0029",
            "name": "getPicture",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getPicture"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetPlaylist\u0028\u0029",
            "name": "getPlaylist",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getPlaylist"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetPlaylist\u0028\u0029",
            "name": "setPlaylist",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_setPlaylist"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetCategories\u0028\u0029",
            "name": "getCategories",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getCategories"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AaddCategory\u0028\u0029",
            "name": "addCategory",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_addCategory"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AremoveCategory\u0028\u0029",
            "name": "removeCategory",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_removeCategory"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003ACHEMIN_IMAGE",
            "name": "CHEMIN_IMAGE",
            "summary": "D\u00E9but\u0020de\u0020chemin\u0020vers\u0020les\u0020images",
            "url": "classes/App-Entity-Formation.html#constant_CHEMIN_IMAGE"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024publishedAt",
            "name": "publishedAt",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_publishedAt"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_title"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_description"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024videoId",
            "name": "videoId",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_videoId"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024playlist",
            "name": "playlist",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_playlist"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024categories",
            "name": "categories",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_categories"
        },                {
            "fqsen": "\\App\\Entity\\Playlist",
            "name": "Playlist",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_getDescription"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_setDescription"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetFormations\u0028\u0029",
            "name": "getFormations",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_getFormations"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AaddFormation\u0028\u0029",
            "name": "addFormation",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_addFormation"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AremoveFormation\u0028\u0029",
            "name": "removeFormation",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_removeFormation"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetCategoriesPlaylist\u0028\u0029",
            "name": "getCategoriesPlaylist",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_getCategoriesPlaylist"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#property_name"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#property_description"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A\u0024formations",
            "name": "formations",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#property_formations"
        },                {
            "fqsen": "\\App\\Entity\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Entity-User.html"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetEmail\u0028\u0029",
            "name": "getEmail",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getEmail"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetEmail\u0028\u0029",
            "name": "setEmail",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setEmail"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUserIdentifier\u0028\u0029",
            "name": "getUserIdentifier",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getUserIdentifier"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetRoles\u0028\u0029",
            "name": "getRoles",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetRoles\u0028\u0029",
            "name": "setRoles",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AeraseCredentials\u0028\u0029",
            "name": "eraseCredentials",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_eraseCredentials"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_email"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024roles",
            "name": "roles",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_roles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_password"
        },                {
            "fqsen": "\\App\\Form\\CategorieType",
            "name": "CategorieType",
            "summary": "Type\u0020de\u0020formulaire\u0020Symfony\u0020pour\u0020Categorie.",
            "url": "classes/App-Form-CategorieType.html"
        },                {
            "fqsen": "\\App\\Form\\CategorieType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-CategorieType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\CategorieType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-CategorieType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\FormationType",
            "name": "FormationType",
            "summary": "Type\u0020de\u0020formulaire\u0020Symfony\u0020pour\u0020Formation.",
            "url": "classes/App-Form-FormationType.html"
        },                {
            "fqsen": "\\App\\Form\\FormationType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-FormationType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\FormationType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-FormationType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\PlaylistType",
            "name": "PlaylistType",
            "summary": "Type\u0020de\u0020formulaire\u0020Symfony\u0020pour\u0020Playlist.",
            "url": "classes/App-Form-PlaylistType.html"
        },                {
            "fqsen": "\\App\\Form\\PlaylistType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-PlaylistType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\PlaylistType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-PlaylistType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Kernel",
            "name": "Kernel",
            "summary": "Noyau\u0020de\u0020l\u0027application\u0020Symfony.",
            "url": "classes/App-Kernel.html"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository",
            "name": "CategorieRepository",
            "summary": "",
            "url": "classes/App-Repository-CategorieRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-CategorieRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/App-Repository-CategorieRepository.html#method_add"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/App-Repository-CategorieRepository.html#method_remove"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003AfindAllForOnePlaylist\u0028\u0029",
            "name": "findAllForOnePlaylist",
            "summary": "Retourne\u0020la\u0020liste\u0020des\u0020cat\u00E9gories\u0020des\u0020formations\u0020d\u0027une\u0020playlist.",
            "url": "classes/App-Repository-CategorieRepository.html#method_findAllForOnePlaylist"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository",
            "name": "FormationRepository",
            "summary": "",
            "url": "classes/App-Repository-FormationRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-FormationRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/App-Repository-FormationRepository.html#method_add"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/App-Repository-FormationRepository.html#method_remove"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindAllOrderBy\u0028\u0029",
            "name": "findAllOrderBy",
            "summary": "Retourne\u0020toutes\u0020les\u0020formations\u0020tri\u00E9es\u0020sur\u0020un\u0020champ.",
            "url": "classes/App-Repository-FormationRepository.html#method_findAllOrderBy"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindByContainValue\u0028\u0029",
            "name": "findByContainValue",
            "summary": "Enregistrements\u0020dont\u0020un\u0020champ\u0020contient\u0020une\u0020valeur\nou\u0020tous\u0020les\u0020enregistrements\u0020si\u0020la\u0020valeur\u0020est\u0020vide.",
            "url": "classes/App-Repository-FormationRepository.html#method_findByContainValue"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindAllLasted\u0028\u0029",
            "name": "findAllLasted",
            "summary": "Retourne\u0020les\u0020n\u0020formations\u0020les\u0020plus\u0020r\u00E9centes.",
            "url": "classes/App-Repository-FormationRepository.html#method_findAllLasted"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindAllForOnePlaylist\u0028\u0029",
            "name": "findAllForOnePlaylist",
            "summary": "Retourne\u0020la\u0020liste\u0020des\u0020formations\u0020d\u0027une\u0020playlist.",
            "url": "classes/App-Repository-FormationRepository.html#method_findAllForOnePlaylist"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindForBackOffice\u0028\u0029",
            "name": "findForBackOffice",
            "summary": "R\u00E9cup\u00E8re\u0020les\u0020formations\u0020pour\u0020le\u0020back\u002Doffice\navec\u0020tri\u0020et\u0020filtres.",
            "url": "classes/App-Repository-FormationRepository.html#method_findForBackOffice"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository",
            "name": "PlaylistRepository",
            "summary": "",
            "url": "classes/App-Repository-PlaylistRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-PlaylistRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/App-Repository-PlaylistRepository.html#method_add"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/App-Repository-PlaylistRepository.html#method_remove"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AfindAllOrderByName\u0028\u0029",
            "name": "findAllOrderByName",
            "summary": "Retourne\u0020toutes\u0020les\u0020playlists\u0020tri\u00E9es\u0020sur\u0020le\u0020nom\u0020de\u0020la\u0020playlist.",
            "url": "classes/App-Repository-PlaylistRepository.html#method_findAllOrderByName"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AfindAllOrderByNbFormations\u0028\u0029",
            "name": "findAllOrderByNbFormations",
            "summary": "Retourne\u0020toutes\u0020les\u0020playlists\u0020tri\u00E9es\u0020sur\u0020le\u0020nombre\u0020de\u0020formations\u0020associ\u00E9es.",
            "url": "classes/App-Repository-PlaylistRepository.html#method_findAllOrderByNbFormations"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AfindByContainValue\u0028\u0029",
            "name": "findByContainValue",
            "summary": "Enregistrements\u0020dont\u0020un\u0020champ\u0020contient\u0020une\u0020valeur\nou\u0020tous\u0020les\u0020enregistrements\u0020si\u0020la\u0020valeur\u0020est\u0020vide.",
            "url": "classes/App-Repository-PlaylistRepository.html#method_findByContainValue"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AfindForBackOffice\u0028\u0029",
            "name": "findForBackOffice",
            "summary": "Playlists\u0020pour\u0020le\u0020back\u002Doffice\u0020avec\u0020tri\u0020et\u0020filtre\u0020sur\u0020le\u0020nom.",
            "url": "classes/App-Repository-PlaylistRepository.html#method_findForBackOffice"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AORDER_ASC",
            "name": "ORDER_ASC",
            "summary": "",
            "url": "classes/App-Repository-PlaylistRepository.html#constant_ORDER_ASC"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AORDER_DESC",
            "name": "ORDER_DESC",
            "summary": "",
            "url": "classes/App-Repository-PlaylistRepository.html#constant_ORDER_DESC"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AFIELD_NAME",
            "name": "FIELD_NAME",
            "summary": "",
            "url": "classes/App-Repository-PlaylistRepository.html#constant_FIELD_NAME"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository",
            "name": "UserRepository",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\UserAuthenticator",
            "name": "UserAuthenticator",
            "summary": "Classe\u0020UserAuthenticator.",
            "url": "classes/App-Security-UserAuthenticator.html"
        },                {
            "fqsen": "\\App\\Security\\UserAuthenticator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Security-UserAuthenticator.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\UserAuthenticator\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "",
            "url": "classes/App-Security-UserAuthenticator.html#method_authenticate"
        },                {
            "fqsen": "\\App\\Security\\UserAuthenticator\u003A\u003AonAuthenticationSuccess\u0028\u0029",
            "name": "onAuthenticationSuccess",
            "summary": "",
            "url": "classes/App-Security-UserAuthenticator.html#method_onAuthenticationSuccess"
        },                {
            "fqsen": "\\App\\Security\\UserAuthenticator\u003A\u003AgetLoginUrl\u0028\u0029",
            "name": "getLoginUrl",
            "summary": "",
            "url": "classes/App-Security-UserAuthenticator.html#method_getLoginUrl"
        },                {
            "fqsen": "\\App\\Security\\UserAuthenticator\u003A\u003ALOGIN_ROUTE",
            "name": "LOGIN_ROUTE",
            "summary": "",
            "url": "classes/App-Security-UserAuthenticator.html#constant_LOGIN_ROUTE"
        },                {
            "fqsen": "\\App\\Security\\UserAuthenticator\u003A\u003A\u0024urlGenerator",
            "name": "urlGenerator",
            "summary": "",
            "url": "classes/App-Security-UserAuthenticator.html#property_urlGenerator"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "namespaces/app-controller.html"
        },                {
            "fqsen": "\\App\\Controller\\Admin",
            "name": "Admin",
            "summary": "",
            "url": "namespaces/app-controller-admin.html"
        },                {
            "fqsen": "\\App\\DataFixtures",
            "name": "DataFixtures",
            "summary": "",
            "url": "namespaces/app-datafixtures.html"
        },                {
            "fqsen": "\\App\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-entity.html"
        },                {
            "fqsen": "\\App\\Form",
            "name": "Form",
            "summary": "",
            "url": "namespaces/app-form.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/app-repository.html"
        },                {
            "fqsen": "\\App\\Security",
            "name": "Security",
            "summary": "",
            "url": "namespaces/app-security.html"
        }            ]
);
